### ISSUE TITLE
Getting started?

### ISSUE THREAD

**Issue by pselle** [jvalen/pixel-art-react#1]
Hi! I wanted to extend your app (add dragabble support) but I got an error starting up

I did `npm install` and then `npm start` and got this:

```
$ npm start

> pixel-art-react@1.0.0 start /Users/pselle200/Projects/pixel-art-react
> node server

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                                                  ^

Error: ENOENT: no such file or directory, open 'config.json'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (app.js:33:30)
    at Module._compile (module.js:425:26)
    at loader (/Users/pselle200/Projects/pixel-art-react/node_modules/babel-register/lib/node.js:130:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/pselle200/Projects/pixel-art-react/node_modules/babel-register/lib/node.js:140:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! pixel-art-react@1.0.0 start: `node server`
npm ERR! Exit status 1
```

I can't tell what the issue is -- any ideas? I haven't used webpack before so idk if that's it.

**Comment by pselle** [comment]
NVM figured out the `development` is the way to run in dev

**Comment by jvalen** [comment]
Hi! 

That would be amazing, thanks for you interest! I should extend the README file to give some guidance for both development and production environment.

In the meanwhile you can go 

```
npm run development
```

Thanks!

**Comment by jvalen** [comment]
Great! Glad that you found out. As I mentioned I will improved the README file with more info asap.
Thanks again!
